knpu_oauth2_client:
    clients:
        google:
            type: google
            client_id: '%env(OAUTH_GOOGLE_CLIENT_ID)%'
            client_secret: '%env(OAUTH_GOOGLE_CLIENT_SECRET)%'
            redirect_route: auth_oauth_check
            redirect_params:
                service: google
            use_state: true
            access_type: offline
            hosted_domain: 'my-events-symfony.onrender.com'
        facebook:
            type: facebook
            client_id: '%env(OAUTH_FACEBOOK_CLIENT_ID)%'
            client_secret: '%env(OAUTH_FACEBOOK_CLIENT_SECRET)%'
            redirect_route: auth_oauth_check
            redirect_params:
                service: facebook
            graph_api_version: 'v22.0'